### ISSUE TITLE
Cookie date in test is causing failures

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Cookies#58]
```

#   Failed test at t/issue32.t line 15.
#          got: 'Set-Cookie3: a="b;c;\"d"; path="/"; domain=example.com; path_spec; expires="2029-11-10 00:13:46Z"; version=0
# '
#     expected: 'Set-Cookie3: a="b;c;\"d"; path="/"; domain=example.com; path_spec; expires="2999-11-06 08:58:34Z"; version=0
# '
# Looks like you failed 1 test of 3.
```

This appears to be related to #56. Ping @bmwiedemann 

See failures here: https://www.cpantesters.org/distro/H/HTTP-Cookies.html?oncpan=1&distmat=1&version=6.06&grade=3 or here http://fast-matrix.cpantesters.org/?dist=HTTP-Cookies

**Comment by bmwiedemann** [comment]
Hmm. Is there something limiting the expiry to 10y from `$NOW` ?
Why does my local build say
```
t/issue32.t ............ ok
```

Probably because it only fails on perl 5.10 and older.
Is there something special with perl versions `<= 5.10` ?

**Comment by oalders** [comment]
Maybe this is helpful? https://stackoverflow.com/questions/39652264/why-perl-cannot-convert-unix-timestamp-over-year-2038

I think we could detect the version of Perl and then use a different date in the test for Perl `<= 5.10` rather than introducing a new test dependency.

**Comment by bmwiedemann** [comment]
Can someone test #59 on perl-5.10 or older?

**Comment by oalders** [comment]
I think we just just release a `TRIAL` dist and it would get smoked on the appropriate machines.
